### ISSUE TITLE
`blob.type` is empty for certain image urls

### ISSUE THREAD

**Issue by searene** [arantes555/electron-fetch#40] opened 2021-10-05 00:57 UTC
I use `electron-fetch` to get some image's blob types, as follows:

```js
const blobType = (await (await fetch(url)).blob()).type
```

It works well in most case, however, blobType is empty when url is the following one:

```
https://thumbor.forbes.com/thumbor/651x436/https://blogs-images.forbes.com/davidbressan/files/2017/07/TORGERSON_2010_Arizona_Meteor_Crater.jpg?width=960
```

blob itself is not empty, here is blob object I got while debugging

```
Blob {
  [Symbol(closed)]: false,
  [Symbol(type)]: '',
  [Symbol(buffer)]: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff db 00 43 00 08 06 06 07 06 05 08 07 07 07 09 09 08 0a 0c 14 0d 0c 0b 0b 0c 19 12 13 0f ... 46592 more bytes>
}
```

So why is blob type empty? I'm using electron-fetch 1.7.4.

**Comment by arantes555** [comment] 2021-10-05 09:48
I am sorry but I cannot reproduce your error. When I try getting the blob type of the link you gave, I get `image/jpeg`.

```
> fetch = require('electron-fetch').default
[Function: fetch] { isRedirect: [Function (anonymous)] }
> getBlobType = async (url) => (await (await fetch(url)).blob()).type 
[AsyncFunction: getBlobType]
> getBlobType("https://thumbor.forbes.com/thumbor/651x436/https://blogs-images.forbes.com/davidbressan/files/2017/07/TORGERSON_2010_Arizona_Meteor_Crater.jpg?width=960").then(console.log)
Promise { <pending> }
> image/jpeg
 
> getBlobType("https://thumbor.forbes.com/thumbor/651x436/https://blogs-images.forbes.com/davidbressan/files/2017/07/TORGERSON_2010_Arizona_Meteor_Crater.jpg?width=960").then(console.log)
Promise { <pending> }
> image/jpeg
```

**Comment by arantes555** [comment] 2021-10-05 09:49
The blob type comes directly from the `content-type` header : https://github.com/arantes555/electron-fetch/blob/master/src/body.js#L66 . Maybe somehow the server does not respond with the header in question when you send the request?

**Comment by searene** [comment] 2021-10-06 16:15
This is the corresponding HTTP request and response(304 Not Modified) I captured.

```
GET http://thumbor.forbes.com/thumbor/651x436/https://blogs-images.forbes.com/davidbressan/files/2017/07/TORGERSON_2010_Arizona_Meteor_Crater.jpg?width=960 HTTP/1.1
Host: thumbor.forbes.com
Proxy-Connection: keep-alive
accept: */*
user-agent: electron-fetch/1.0 electron (+https://github.com/arantes555/electron-fetch)
accept-encoding: gzip,deflate
connection: close
Accept-Language: en-US
If-None-Match: "dEVNir27sbw2Nf3gqwJJDu1CkOf4i4gph2z1W/ymXHo"

HTTP/1.1 304 Not Modified
Age: 546878
Connection: keep-alive
Date: Wed, 06 Oct 2021 15:55:26 GMT
Etag: "dEVNir27sbw2Nf3gqwJJDu1CkOf4i4gph2z1W/ymXHo"
Keep-Alive: timeout=4
Proxy-Connection: keep-alive
Via: 1.1 varnish
X-Cache: HIT
X-Cache-Hits: 1
X-Served-By: cache-qpg1252-QPG
X-Timer: S1633535726.317260,VS0,VE1
```

**Comment by searene** [comment] 2021-10-07 00:16
> As for this precise problem, it may be a Chromium or electron bug. Which electron version are you using ?

I started this experiment using a brand new project, which meant I was using the latest version of `electron`, which is `15.1.1`

I've attached the minimal project that I used to test this issue. You can check if you can reproduce the issue from it. Just run `npm install` then `npm start`, the blob will be printed in the console.

[electron-test.zip](https://github.com/arantes555/electron-fetch/files/7297777/electron-test.zip)

**Comment by arantes555** [comment] 2021-10-24 00:42
Sorry for the delayed response : it's actually a known electron bug, see https://github.com/electron/electron/issues/27895 . Nothing I can do until it's fixed on Electron's side, sorry. I'm closing this issue.

**Closed by arantes555** 2021-10-24 00:42 UTC
